"""add composite indexes for tenant-scoped pagination

Revision ID: 30f0d74f7e6e
Revises: ec7fec2220cb
Create Date: 2026-08-05 01:04:11.882186

"""
from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '30f0d74f7e6e'
down_revision: str | Sequence[str] | None = 'ec7fec2220cb'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_audit_events_tenant_id_timestamp_id', 'audit_events', ['tenant_id', 'timestamp', 'id'], unique=False)
    op.create_index('ix_documents_tenant_id_created_at', 'documents', ['tenant_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_documents_tenant_id_created_at', table_name='documents')
    op.drop_index('ix_audit_events_tenant_id_timestamp_id', table_name='audit_events')
    # ### end Alembic commands ###
