"""add audit_chain_state table for row-locked chain appends

Revision ID: ed3a4f8a50b6
Revises: 30f0d74f7e6e
Create Date: 2026-08-05 22:08:32.950849

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'ed3a4f8a50b6'
down_revision: str | Sequence[str] | None = '30f0d74f7e6e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_chain_state',
    sa.Column('tenant_id', sa.String(length=255), nullable=False),
    sa.Column('latest_event_hash', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('tenant_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('audit_chain_state')
    # ### end Alembic commands ###
